# Generated by Django 3.1.6 on 2021-03-04 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('is_student', models.BooleanField(default=True, verbose_name='é estudante?')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.turma')),
            ],
        ),
    ]
