# Generated by Django 2.2.9 on 2021-03-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Turma'),
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
    ]
